import Head from 'next/head'
import React, { useState, useEffect } from 'react'
import Request from './api/request'
import RowMovies from '../Components/RowMovies'


import { IoIosInformationCircleOutline } from "react-icons/io";

export default function Home() {

  const [movies, setMovies] = useState([])

  useEffect(() => {
    const req = async () => {
      let list = await Request.getHomeList()
      setMovies(list)
      console.log(list)
    }

    req();
  }, [])


  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='home_contente'>

        <div className="container-image">
          <h1 className='title'>Duna</h1>
          <div>
          <button className='watch-button'><span>&#9658;</span> Assistir </button>
          <button className='info-button'><span><IoIosInformationCircleOutline /></span>Mais informações</button>
          </div>
        </div>
        {
          movies.map((item, index) => (
            <div>
              <RowMovies items={item.item} title={item.title} key={index} />
            </div>
          ))
        }
      </div>
    </div>
  )
}


/* export async function getStaticProps() {

  const response = await fetch(`https://api.themoviedb.org/3/discover/tv?with_network=8&language=pt-BR&api_key=9fc5ec823b52d89bc85b0d989845ac55`)
  const data = await response.json()

  return {
    props: {
      movie: data.results,
    },
    revalidate: 10,
  }
}
 */

/* https://api.themoviedb.org/3/discover/tv?with_network=8&language=pt-BR&api_key=9fc5ec823b52d89bc85b0d989845ac55 */

/*https://api.themoviedb.org/3/discover/tv?api_key=9fc5ec823b52d89bc85b0d989845ac55&with_network=213&language=pt  */


/*

const [movies, setMovies] = useState([])

useEffect(()=>{
  const req = async () =>{
    let list = await request.getHomeList()
    setMovies(list)
  }

  req();
},[])


*/